"""empty message

Revision ID: 095af646402d
Revises: 3c31d6a85ac7
Create Date: 2021-12-14 23:05:16.421691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095af646402d'
down_revision = '3c31d6a85ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
